AppBarragem.WEB.ADM/Controllers/ExamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mamelucos.WEB.ADM.Controllers
{
    public class ExamplesController : Controller
    {
        // GET: Examples
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Page404()
        {
            return View();
        }

        public ActionResult Page500()
        {
            return View();
        }

        public ActionResult Blank()
        {
            return View();
        }

        public ActionResult InvoicePrint()
        {
            return View();
        }

        public ActionResult Invoice()
        {
            return View();
        }

        public ActionResult Lockscreen()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Pace()
        {
            return View();
        }

        public ActionResult PageProfile()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
    }
}

AppBarragem.WEB.ADM/Controllers/LoginController.cs
using ZeNerd.DAL.Context;
using AppBarragem.Utils;
using AppBarragem.WEB.ADM.Util;
using System;
using System.Linq;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AppBarragem.WEB.ADM.Controllers
{
    //[WebAuthorize(TipoUsuario.Admin, TipoUsuario.SuperAdmin)]

    public class LoginController : Controller
    {
        private DatabaseContext db = new DatabaseContext();
        private Usuario objUsuario;

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        // GET: Login
        public ActionResult Reiniciar()
        {
            return View();
        }

        public async Task<ActionResult> EnviarSenha(Usuario model)
        {
            model = db.Usuario.Where(i => i.Email == model.Email).FirstOrDefault();

            //connection = new EmailConnection(Suporte.Email, Suporte.Senha, Suporte.Host, Suporte.Porta, Suporte.SSL);

            ResgatarSenha(model.Email, model.Nome, model.Senha);
            //Services.EnviarEmail.RecuperarSenha(model.Email, model.Nome, model.Senha);

            return View("Index");
        }

        public static void ResgatarSenha(string EmailTo, string Nome, string Senha)
        {
            MailMessage mail = new MailMessage();
            mail.To.Add(EmailTo);
            mail.From = new MailAddress(Suporte.Email);
            mail.Subject = "[Mamelukos] Recuperação de senha - " + DateTime.Now.ToString();
            mail.Body = $@"
                            <!DOCTYPE html>
                            <html lang='pt-br' xmlns='http://www.w3.org/1999/xhtml'>
                            <head>
                                <meta charset='utf-8' />
                                <title>Mamelukos</title>
                                <link href='https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css' rel='stylesheet'>
                            </head>
                            <body style='width: 720px; margin: auto;'>
                                <div style='padding: 24px; background-color: white; text-align: center;'>
                                    <img src='' />
                                    <hr style='background-color: #E5312A; border-color: #E5312A; color: #E5312A;' />
                                </div>
                                <div>
                                    <p style='margin: 24px 48px; color: #E5312A;'>Olá, <strong>{Nome}</strong></p>
                                    <div style='font-weight: bold; background-color: #00A859; color: white;'>
                                        <p style='margin: 24px 48px; padding: 16px 0px; line-height: 2;'>
                                            Foi solicitado uma recuperação de senha para esta conta.
                                            <br />
                                            Sua nova senha é: {Senha}
                                        </p>
                                    </div>
                                    <p style='margin: 24px 48px; color: #E5312A; line-height: 2;'>
                                        Atenciosamente,
                                        <br />
                                        <strong>Equipe Mamelukos</strong>
                                    </p>
                                </div>
                            </body>
                            </html>
                            ";
            mail.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient(Suporte.Host, Suporte.Porta);
            smtp.EnableSsl = Suporte.SSL;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new System.Net.NetworkCredential(Suporte.Email, Suporte.Senha);
            smtp.Send(mail);
        }

        //        public static async Task<bool> RecuperarSenha(string email, string nome, string senha)
        //        {
        //            var body = $@"
        //<!DOCTYPE html>
        //<html lang='pt-br' xmlns='http://www.w3.org/1999/xhtml'>
        //<head>
        //    <meta charset='utf-8' />
        //    <title>Mamelukos</title>
        //    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css' rel='stylesheet'>
        //</head>
        //<body style='width: 720px; margin: auto;'>
        //    <div style='padding: 24px; background-color: white; text-align: center;'>
        //        <img src='' />
        //        <hr style='background-color: #E5312A; border-color: #E5312A; color: #E5312A;' />
        //    </div>
        //    <div>
        //        <p style='margin: 24px 48px; color: #E5312A;'>Olá, <strong>{nome}</strong></p>
        //        <div style='font-weight: bold; background-color: #00A859; color: white;'>
        //            <p style='margin: 24px 48px; padding: 16px 0px; line-height: 2;'>
        //                Foi solicitado uma recuperação de senha para esta conta.
        //                <br />
        //                Sua nova senha é: {senha}
        //            </p>
        //        </div>
        //        <p style='margin: 24px 48px; color: #E5312A; line-height: 2;'>
        //            Atenciosamente,
        //            <br />
        //            <strong>Equipe Mamelukos</strong>
        //        </p>
        //    </div>
        //</body>
        //</html>
        //";
        //            return (await connection.SendHtml(email, "[Mamelukos] Recuperação de senha", body)).IsSuccess;
        // é só referenciar qual a classe pra tirar a ambiguidade
        //        }

        // GET: Login
        public ActionResult Sair()
        {
            Request.GetOwinContext().Authentication.SignOut(Utils.Constantes.IDENTITY_UUID);
            var AuthenticationManager = HttpContext.GetOwinContext().Authentication;
            AuthenticationManager.SignOut();
            return RedirectToAction("../Login/Index");
        }

        // vc criar um contlher home pso pra chamar essas constantes
        // a view vai chamar essa Action, que vai retornar a url
        // pode chamar em qualquer lugar... é só vc reerenciar o controlhe e a action
        public string UrlImagem()
        {
            //return string.Empty;
            return this.GetUserImage();
        }

        // GET: Login
        public async System.Threading.Tasks.Task<ActionResult> Login(Usuario model)
        {
            Usuario usuario = db.Usuario.ToList().Where(i => (i.Login == model.Login) && (i.Senha == Utils.Constantes.SHA1Encode(model.Senha))).FirstOrDefault();



            if (usuario != null)
            {
                //Constantes.USER_LOCAL_IMAGEM = usuario.Foto;
                //Util.Constantes.USUARIO_LOGADO = usuario;
                var identity = new ClaimsIdentity(new[] {
            new Claim(ClaimTypes.Name, usuario.Nome),
            new Claim(ClaimTypes.Email, usuario.Email),
            new Claim(ClaimTypes.Thumbprint, usuario.Foto),
            new Claim(ClaimTypes.NameIdentifier, usuario.Id.ToString()), //should be userid
                 new Claim(ClaimTypes.Role,  VerificaRegraAcesso(usuario.TipoUsuario.ToString()))
            }, "ApplicationCookie");

                Request.GetOwinContext().Authentication.SignOut(Utils.Constantes.IDENTITY_UUID);
                Request.GetOwinContext().Authentication.SignIn(identity);

                return RedirectToAction("../Home/Index");
            }
            else
            {
                TempData.Add("ATENCAO",
          "O usuário ou senha estão inválidos!");
                return RedirectToAction("/Index");
            }
        }

        private string VerificaRegraAcesso(string tipo)
        {
            switch (tipo)
            {
                case "0":
                    return "SuperAdmin";

                case "1":
                    return "Admin";

                case "2":
                    return "User";

                default:
                    return "User";
            }
        }
    }
}

AppBarragem.WEB.ADM/Views/Examples/Blank.cshtml
@{
    ViewBag.Title = "Blank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Blank page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Title</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                Start creating your amazing application!
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                Footer
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

AppBarragem.WEB.ADM/Views/Examples/Invoice.cshtml
@{
    ViewBag.Title = "Invoice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Invoice
            <small>#007612</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Invoice</li>
        </ol>
    </section>
    <div class="pad margin no-print">
        <div class="callout callout-info" style="margin-bottom: 0!important;">
            <h4><i class="fa fa-info"></i> Note:</h4>
            This page has been enhanced for printing. Click the print button at the bottom of the invoice to test.
        </div>
    </div>
    <!-- Main content -->
    <section class="invoice">
        <!-- title row -->
        <div class="row">
            <div class="col-xs-12">
                <h2 class="page-header">
                    <i class="fa fa-globe"></i> AppBarragem.WEB.ADM, Inc.
                    <small class="pull-right">Date: 2/10/2014</small>
                </h2>
            </div>
            <!-- /.col -->
        </div>
        <!-- info row -->
        <div class="row invoice-info">
            <div class="col-sm-4 invoice-col">
                From
                <address>
                    <strong>Admin, Inc.</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    Phone: (804) 123-5432<br>
                    Email: info@almasaeedstudio.com
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                To
                <address>
                    <strong>John Doe</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    Phone: (555) 539-1037<br>
                    Email: john.doe@example.com
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                <b>Invoice #007612</b><br>
                <br>
                <b>Order ID:</b> 4F3S8J<br>
                <b>Payment Due:</b> 2/22/2014<br>
                <b>Account:</b> 968-34567
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- Table row -->
        <div class="row">
            <div class="col-xs-12 table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Qty</th>
                            <th>Product</th>
                            <th>Serial #</th>
                            <th>Description</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>Call of Duty</td>
                            <td>455-981-221</td>
                            <td>El snort testosterone trophy driving gloves handsome</td>
                            <td>$64.50</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Need for Speed IV</td>
                            <td>247-925-726</td>
                            <td>Wes Anderson umami biodiesel</td>
                            <td>$50.00</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Monsters DVD</td>
                            <td>735-845-642</td>
                            <td>Terry Richardson helvetica tousled street art master</td>
                            <td>$10.70</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Grown Ups Blue Ray</td>
                            <td>422-568-642</td>
                            <td>Tousled lomo letterpress</td>
                            <td>$25.99</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <div class="row">
            <!-- accepted payments column -->
            <div class="col-xs-6">
                <p class="lead">Payment Methods:</p>
                <img src="~/Content/AppBarragem.WEB.ADM/img/credit/visa.png" alt="Visa">
                <img src="~/Content/AppBarragem.WEB.ADM/img/credit/mastercard.png" alt="Mastercard">
                <img src="~/Content/AppBarragem.WEB.ADM/img/credit/american-express.png" alt="American Express">
                <img src="~/Content/AppBarragem.WEB.ADM/img/credit/paypal2.png" alt="Paypal">
                <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                    Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem plugg
                    dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
                </p>
            </div>
            <!-- /.col -->
            <div class="col-xs-6">
                <p class="lead">Amount Due 2/22/2014</p>
                <div class="table-responsive">
                       <table id="example1" class="table table-bordered table-striped">
                        <tr>
                            <th style="width:50%">Subtotal:</th>
                            <td>$250.30</td>
                        </tr>
                        <tr>
                            <th>Tax (9.3%)</th>
                            <td>$10.34</td>
                        </tr>
                        <tr>
                            <th>Shipping:</th>
                            <td>$5.80</td>
                        </tr>
                        <tr>
                            <th>Total:</th>
                            <td>$265.24</td>
                        </tr>
                    </table>
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <!-- this row will not appear when printing -->
        <div class="row no-print">
            <div class="col-xs-12">
                <a href="@Url.Action("InvoicePrint", "Examples")" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>
                <button type="button" class="btn btn-success pull-right">
                    <i class="fa fa-credit-card"></i> Submit Payment
                </button>
                <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
                    <i class="fa fa-download"></i> Generate PDF
                </button>
            </div>
        </div>
    </section>
    <!-- /.content -->
    <div class="clearfix"></div>
</div>
<!-- /.content-wrapper -->

AppBarragem.WEB.ADM/Views/Examples/Lockscreen.cshtml
@{
    ViewBag.Title = "Lockscreen";
    Layout = "";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AppBarragem.WEB.ADM 2 | Lockscreen</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/AppBarragem.WEB.ADM/css/AppBarragem.WEB.ADM.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/plugins/iCheck/square/blue.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition lockscreen">
    <!-- Automatic element centering -->
    <div class="lockscreen-wrapper">
        <div class="lockscreen-logo">
            <a href="@Url.Action("Index", "Home")" class="navbar-brand"><b>Admin</b>Deseo</a>
        </div>
        <!-- User name -->
        <div class="lockscreen-name">John Doe</div>
        <!-- START LOCK SCREEN ITEM -->
        <div class="lockscreen-item">
            <!-- lockscreen image -->
            <div class="lockscreen-image">
                <img src="~/Content/AppBarragem.WEB.ADM/img/user1-128x128.jpg" alt="User Image">
            </div>
            <!-- /.lockscreen-image -->
            <!-- lockscreen credentials (contains the form) -->
            <form class="lockscreen-credentials">
                <div class="input-group">
                    <input type="password" class="form-control" placeholder="password">
                    <div class="input-group-btn">
                        <button type="button" class="btn"><i class="fa fa-arrow-right text-muted"></i></button>
                    </div>
                </div>
            </form>
            <!-- /.lockscreen credentials -->
        </div>
        <!-- /.lockscreen-item -->
        <div class="help-block text-center">
            Enter your password to retrieve your session
        </div>
        <div class="text-center">
            <a href="@Url.Action("Login", "Examples")">Or sign in as a different user</a>
        </div>
        <div class="lockscreen-footer text-center">
            Copyright &copy; 2014-2016 <b><a href="https://AppBarragem.WEB.ADM.io" class="text-black">Jxis</a></b><br>
            All rights reserved
        </div>
    </div>
    <!-- /.center -->
    <!-- jQuery 3 -->
    <script src="~/Scripts/AppBarragem.WEB.ADM/components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Scripts/AppBarragem.WEB.ADM/components/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>

AppBarragem.WEB.ADM/Views/Examples/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AppBarragem.WEB.ADM 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/AppBarragem.WEB.ADM/css/AppBarragem.WEB.ADM.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/plugins/iCheck/square/blue.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>Deseo</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Sign in to start your session</p>
            <form action="@Url.Action("Dashboardv2", "Dashboard")" method="post">
                <div class="form-group has-feedback">
                    <input type="email" class="form-control" placeholder="Email">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="Password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox"> Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
            <div class="social-auth-links text-center">
                <p>- OR -</p>
                <a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
                    <i class="fa fa-facebook"></i> Sign in using
                    Facebook
                </a>
                <a href="#" class="btn btn-block btn-social btn-google btn-flat">
                    <i class="fa fa-google-plus"></i> Sign in using
                    Google+
                </a>
            </div>
            <!-- /.social-auth-links -->
            <a href="#">I forgot my password</a><br>
            <a href="@Url.Action("Register", "Examples")" class="text-center">Register a new membership</a>
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery 3 -->
    <script src="~/Scripts/AppBarragem.WEB.ADM/components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Scripts/AppBarragem.WEB.ADM/components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="~/Scripts/AppBarragem.WEB.ADM/plugins/iCheck/icheck.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' /* optional */
        });
      });
    </script>
</body>
</html>

AppBarragem.WEB.ADM/Views/Examples/Register.cshtml
@{
    ViewBag.Title = "Register";
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AppBarragem.WEB.ADM 2 | Registration Page</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/AppBarragem.WEB.ADM/css/AppBarragem.WEB.ADM.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Scripts/AppBarragem.WEB.ADM/plugins/iCheck/square/blue.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a href="@Url.Action("Dashboardv2", "Dashboard")"><b>Admin</b>Deseo</a>
        </div>
        <div class="register-box-body">
            <p class="login-box-msg">Register a new membership</p>
            <form action="@Url.Action("Dashboardv2", "Dashboard")" method="post">
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" placeholder="Full name">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="email" class="form-control" placeholder="Email">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="Password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="Retype password">
                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox"> I agree to the <a href="#">terms</a>
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
            <div class="social-auth-links text-center">
                <p>- OR -</p>
                <a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
                    <i class="fa fa-facebook"></i> Sign up using
                    Facebook
                </a>
                <a href="#" class="btn btn-block btn-social btn-google btn-flat">
                    <i class="fa fa-google-plus"></i> Sign up using
                    Google+
                </a>
            </div>
            <a href="@Url.Action("Login", "Examples")" class="text-center">I already have a membership</a>
        </div>
        <!-- /.form-box -->
    </div>
    <!-- /.register-box -->
    <!-- jQuery 3 -->
    <script src="~/Scripts/AppBarragem.WEB.ADM/components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Scripts/AppBarragem.WEB.ADM/components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="~/Scripts/AppBarragem.WEB.ADM/plugins/iCheck/icheck.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' /* optional */
        });
      });
    </script>
</body>
</html>