AppBarragem.WEB.ADM/Controllers/AlertaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppBarragem.WEB.ADM.Controllers
{
    public class AlertaController : Controller
    {
        // GET: Alerta
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ChamarAlerta(FormCollection formCollection)
        {
            string nome = formCollection["name"];
            string mensagem = formCollection["message"];

            AppBarragem.Services.EnviarNotificacao.ParaTodos(nome, mensagem);

            return RedirectToAction("Index");
        }
        
        // GET: Alerta/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Alerta/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Alerta/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Alerta/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Alerta/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Alerta/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Alerta/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AppBarragem.WEB.ADM/Views/Alerta/Index.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutCrud.cshtml";
}

<style>
    body {
        background: #F06060;
    }

    h1 {
        color: #AB3C3C;
        text-align: center;
        font-family: Arial;
        font-size: 50px;
        font-weight: normal;
    }

    button {
        background: none repeat scroll 0 0 #CB4E4E;
        border-radius: 100px;
        box-shadow: 0 8px #AB3C3C;
        color: #FFFFFF;
        width: 150px;
        height: 150px;
        border: 0px;
        cursor: pointer;
        position: relative;
        font-size: 25px;
        display: block;
    }


        button:hover {
            box-shadow: 0px 5px #AB3C3C;
            top: 2px;
        }

        button:active {
            box-shadow: 0px 0px #AB3C3C;
            top: 5px;
        }

    #contact {
        padding: 10px 0 10px;
    }

    .contact-text {
        margin: 45px auto;
    }

    .mail-message-area {
        width: 100%;
        padding: 0 15px;
    }

    .mail-message {
        width: 100%;
        background: rgba(255,255,255, 0.8) !important;
        -webkit-transition: all 0.7s;
        -moz-transition: all 0.7s;
        transition: all 0.7s;
        margin: 0 auto;
        border-radius: 0;
    }

    .not-visible-message {
        height: 0px;
        opacity: 0;
    }

    .visible-message {
        height: auto;
        opacity: 1;
        margin: 25px auto 0;
    }

    /* Input Styles */

    .form {
        width: 100%;
        padding: 15px;
        background: #f8f8f8;
        border: 1px solid rgba(0, 0, 0, 0.075);
        margin-bottom: 25px;
        color: #727272 !important;
        font-size: 13px;
        -webkit-transition: all 0.4s;
        -moz-transition: all 0.4s;
        transition: all 0.4s;
    }

        .form:hover {
            border: 1px solid #8BC3A3;
        }

        .form:focus {
            color: white;
            outline: none;
            border: 1px solid #8BC3A3;
        }

    .textarea {
        height: 200px;
        max-height: 200px;
        max-width: 100%;
    }

    /* Generic Button Styles */

    .button {
        padding: 8px 12px;
        background: #0A5175;
        display: block;
        width: 120px;
        margin: 10px 0 0px 0;
        border-radius: 3px;
        -webkit-transition: all 0.3s;
        -moz-transition: all 0.3s;
        transition: all 0.3s;
        text-align: center;
        font-size: 0.8em;
        box-shadow: 0px 1px 4px rgba(0,0,0, 0.10);
        -moz-box-shadow: 0px 1px 4px rgba(0,0,0, 0.10);
        -webkit-box-shadow: 0px 1px 4px rgba(0,0,0, 0.10);
    }

        .button:hover {
            background: #8BC3A3;
            color: white;
        }

    /* Send Button Styles */

    .form-btn {
        width: 480px;
        display: block;
        height: auto;
        padding: 15px;
        color: #fff;
        background: #8BC3A3;
        border: none;
        border-radius: 3px;
        outline: none;
        -webkit-transition: all 0.3s;
        -moz-transition: all 0.3s;
        transition: all 0.3s;
        margin: auto;
        box-shadow: 0px 1px 4px rgba(0,0,0, 0.10);
        -moz-box-shadow: 0px 1px 4px rgba(0,0,0, 0.10);
        -webkit-box-shadow: 0px 1px 4px rgba(0,0,0, 0.10);
    }

        .form-btn:hover {
            background: #111;
            color: white;
            border: none;
        }

        .form-btn:active {
            opacity: 0.9;
        }

    center {
        margin-top: 330px;
    }

    input {
        position: relative;
        z-index: 9999;
    }
</style>

@*<h2>Alerta de Rompimento de Barragem</h2>*@


@using (Html.BeginForm("ChamarAlerta", "Alerta", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div>
        @Html.ActionLink("Retornar", "Index")
    </div>
    <div id="alinhar">
        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <h1>Alerta de Rompimento de Barragem</h1>

            <div class="inner contact">
                <!-- Form Area -->
                <div class="contact-form" style=" margin:0 auto; text-align:center;align-content:center;align-self:center;">

                    <p>
                        <!-- Left Inputs -->
                        <div class="col-xs-6 wow animated slideInLeft" data-wow-delay=".5s">
                            <!-- Name -->
                            <input type="text" name="name" id="name" required="required" class="form" placeholder="Titulo do alerta" />
                            <textarea name="message" id="message" class="form textarea" required="required" placeholder="Mensagem Alerta"></textarea>
                        </div><!-- End Left Inputs -->
                        <!-- Right Inputs -->
                    </p>
                    <br />
                    <hr />
                    <p>

                    </p>
                    <!-- Bottom Submit -->
                    <!-- Clear -->
                    <div class="clear"></div>


                    <!-- Your Mail Message -->
                    <div class="mail-message-area">
                        <!-- Message -->
                        <div class="alert gray-bg mail-message not-visible-message">
                            <strong>Thank You !</strong> Your email has been delivered.
                        </div>
                    </div>

                </div><!-- End Contact Form Area -->
            </div><!-- End Inner -->


        </div>
    </div>
    <button id="error">Alertar!</button>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}